import Head from 'next/head';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillGithub, AiFillLinkedin, AiFillInstagram } from 'react-icons/ai';
import Image from 'next/image';
import profilepic from '../../public/profile_pic.png';
import design from '../../public/design.png';
import consulting from '../../public/consulting.png';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Charlie Kake-White Portfolio</title>
        <meta name='description' content='generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40'>
        <section className='min-h-screen'>
        <div class="hidden sm:ml-6 sm:block">
          <div class="flex space-x-4">
            <a href="#" class="bg-gray-900 text-white rounded-md px-3 py-2 text-sm font-medium" aria-current="page">Career Goals</a>
            <a href="#" class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium">Work Experience</a>
            <a href="#" class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium">Projects</a>
            <a href="#" class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium">Hobbies</a>
          </div>

          
        </div>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-sans'>TODO: Insert online media handle</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill className='cursor-pointer text-2xl' />
              </li>
              {/* TODO: Functionality to create resume on button click */}
              <li>
                <a className='bg-gradient-to-r from-cyan-500 to-teal-500 bg-cyan-500 text-2xl text-white px-4 py-2 rounded-md ml-8 font-medium' href='#'>
                  Résumé
                </a>
              </li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-grey-600 font-medium'>Charlie Kake-White</h2>
            <h3 className='text-xl p-10'>Aspiring Software Engineer | Full Stack Developer</h3>
            <p className='text-md py-2 leading-8 text-grey-800 font-medium'>
              Hello! Welcome to my portfolio. I am a computer systems engineering student focused on full stack development.
              With expertise in hardware and software systems alike, I strive to create exceptional solutions.
              Let's connect and explore the possibilities together.
            </p>
          </div>
          {/* TODO: Implement url routing on click to these buttons */}
          <div className='text-5xl flex justify-center gap-16 py-3 text-grey-800'>
            <AiFillGithub />
            <AiFillLinkedin />
            <AiFillInstagram />
          </div>
          <div className='mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96'>
            <div className='-m-5'>
              <Image src={profilepic} layout='fill' objectFit='cover' alt='portfolio-picture' />
            </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className='text-3xl py-5 leading-8 text-grey-800 text-center font-medium'>Career Goals</h3>
            <p className='text-md py-2 leading-8 text-grey-800 font-medium'>
              I am currently in my penultimate year studying Computer Systems Engineering at the University of Auckland.
              I aspire to pursue a career that combines my hardware and software expertise, aiming for a role that fosters
              growth in <span className='text-teal-500 text-md py-2 leading-8 text-grey-800'>software development</span> and eventually
              <span className='text-teal-500 text-md py-2 leading-8 text-grey-800'> full stack capabilities</span>.
              In this rapidly evolving industry, securing a position now would provide invaluable opportunities,
              given the exponential advancements in technology and software.
            </p>
          </div>

          <div>
            <div className='py-10'>
              <h3 className='text-3xl py-2 leading-8 text-grey-800 text-center font-medium'>Work Experience</h3>
            </div>
              <ol className='border-l border-neutral-300 dark:border-neutral-500 md:flex md:justify-center md:gap-6 md:border-l-0 md:border-t'>
              <li>
                <div className='flex-start flex items-center pt-2 md:block md:pt-0'>
                  <div className='-ml-[5px] mr-3 h-[9px] w-[9px] rounded-full bg-neutral-300 dark:bg-neutral-500 md:-mt-[5px] md:ml-0 md:mr-0'></div>
                  <p className='mt-2 text-sm text-neutral-500 dark:text-neutral-300 font-medium'>
                    2020 - current
                  </p>
                </div>
                <div className='ml-4 mt-2 pb-5 md:ml-0'>
                  <h4 className='mb-1.5 text-xl font-medium'>
                    The Grove Restaurant
                  </h4>
                  <ul className='list-disc'>
                    <li className='leading-8 font-medium'>Nationally renowned restaurant, therefore the highest level of customer service is required.</li>
                    <li className='leading-8 font-medium'>Gained the ability to work in a high-stress environment while continuing to focus on customer service.</li>
                    <li className='leading-8 font-medium'>Proactively answering customer inquiries and complaints.</li>
                  </ul>
                </div>
              </li>
              <li>
                <div className='flex-start flex items-center pt-2 md:block md:pt-0'>
                  <div className='-ml-[5px] mr-3 h-[9px] w-[9px] rounded-full bg-neutral-300 dark:bg-neutral-500 md:-mt-[5px] md:ml-0 md:mr-0'></div>
                  <p className='mt-2 text-sm text-neutral-500 dark:text-neutral-300 font-medium'>
                    2022 - 2023
                  </p>
                </div>
                <div className='ml-4 mt-2 pb-5 md:ml-0'>
                  <h4 className='mb-1.5 text-xl font-medium'>
                    University Tutor
                  </h4>
                  <ul className='list-disc'>
                    <li className='leading-8 font-medium'>Tutor for first-year engineering students.</li>
                    <li className='leading-8 font-medium'>Assisted students in developing study skills, time management strategies, and problem-solving techniques.</li>
                    <li className='leading-8 font-medium'>Monitored and evaluated student progress, providing feedback to encourage academic improvement.</li>
                  </ul>
                </div>
              </li>
              <li>
                <div className='flex-start flex items-center pt-2 md:block md:pt-0'>
                  <div className='-ml-[5px] mr-3 h-[9px] w-[9px] rounded-full bg-neutral-300 dark:bg-neutral-500 md:-mt-[5px] md:ml-0 md:mr-0'></div>
                  <p className='mt-2 text-sm text-neutral-500 dark:text-neutral-300 font-medium'>
                    2022 - 2023 (Summer Internship)
                  </p>
                </div>
                <div className='ml-4 mt-2 pb-5 md:ml-0'>
                  <h4 className='mb-1.5 text-xl font-medium'>MYOB Intern Developer</h4>
                  <ul className='list-disc'>
                    <li className='leading-8 font-medium'>Completed a 3-week acceleration program, focusing on core software development concepts such as TDD and OOP</li>
                    <li className='leading-8 font-medium'>Collaborated with fellow interns on a 6-week cohort project, delivering an ehanced and refined client-facing product. </li>
                    <li className='leading-8 font-medium'>Gained exposure to a professional development team's work environment and day-to-day agile methodologies through team-shadowing.</li>
                    <li className='leading-8 font-medium'>Participated and won the MYOB Hackathon, developing prototype for company-wide problem.</li>
                  </ul>
                </div>
              </li>
            </ol>
          </div>
          {/* TODO: Implement Project Modals */}
          <h3 className='text-3xl py-2 leading-8 text-grey-800 text-center font-medium'>Projects</h3>
          <div className="flex justify-center">
            <div className="text-center bg-blue-100 shadow-lg p-6 rounded-xl my-10 mx-4 dark:bg-blue-800">
              {/* <Image src={design} width={80} height={80} /> */}
              <h3 className="text-md font-medium pt-6 pb-2">Capstone Project</h3>
            </div>

            <div className="text-center bg-blue-100 shadow-lg p-6 rounded-xl my-10 mx-4 dark:bg-blue-800">
              {/* <Image src={design} width={80} height={80} /> */}
              <h3 className="text-md font-medium pt-6 pb-2">Part IV Research Project</h3>
            </div>

            <div className="text-center bg-blue-100 shadow-lg p-6 rounded-xl my-10 mx-4 dark:bg-blue-800">
              {/* <Image src={design} width={80} height={80} /> */}
              <h3 className="text-md font-medium pt-6 pb-2">MYOB Cohort Project</h3>
            </div>
          </div>

          

        
        </section>
      </main>
    </div>
  );
}
